// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protobuf.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Pb {

  /// <summary>Holder for reflection information generated from Protobuf.proto</summary>
  public static partial class ProtobufReflection {

    #region Descriptor
    /// <summary>File descriptor for Protobuf.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtobufReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5Qcm90b2J1Zi5wcm90bxICcGIiGwoLQWNjb3VudERhdGESDAoEbmFtZRgB",
            "IAEoCSJTCgpTZWxlY3REYXRhEhIKCnBsYXllck5hbWUYAiABKAkSDwoHY2hh",
            "dE1lcxgDIAEoCRIPCgdmYWN0aW9uGAYgASgFEg8KB2lzUmVhZHkYByABKAgi",
            "+gQKCVBiTWVzc2FnZRIMCgRuYW1lGAEgASgJEh4KA2NtZBgCIAEoDjIRLnBi",
            "LlBiTWVzc2FnZS5DTUQSKAoIY21kTWF0Y2gYAyABKA4yFi5wYi5QYk1lc3Nh",
            "Z2UuQ21kTWF0Y2gSJgoHY21kUm9vbRgEIAEoDjIVLnBiLlBiTWVzc2FnZS5D",
            "bWRSb29tEhEKCXJvb21JbmRleBgFIAEoBRIPCgdjaGF0TWVzGAYgASgJEiIK",
            "CnNlbGVjdERhdGEYByABKAsyDi5wYi5TZWxlY3REYXRhEiYKDnJvb21TZWxl",
            "Y3REYXRhGAggAygLMg4ucGIuU2VsZWN0RGF0YRITCgtsb2FkUGVyY2VudBgJ",
            "IAEoBRIXCg9yb29tTG9hZFBlcmNlbnQYCiADKAUSDwoHZnJhbWVJZBgLIAEo",
            "BRIqChBzZW5kRmlnaHRNZXNzYWdlGAwgASgLMhAucGIuRmlnaHRNZXNzYWdl",
            "EiYKDGZpZ2h0TWVzc2FnZRgNIAMoCzIQLnBiLkZpZ2h0TWVzc2FnZSJICgND",
            "TUQSCQoFbG9naW4QABIJCgVtYXRjaBABEggKBHJvb20QAhIJCgVmaWdodBAD",
            "EggKBGNoYXQQBBIMCghmaWdodEVuZBAFIigKCENtZE1hdGNoEg0KCWpvaW5N",
            "YXRjaBAAEg0KCXF1aXRNYXRjaBABInYKB0NtZFJvb20SCwoHY29uZmlybRAA",
            "EgoKBnNlbGVjdBABEg4KCnNlbGVjdERhdGUQAhIICgRsb2FkEAMSDAoIbG9h",
            "ZERhdGEQBBIOCgpmaWdodFN0YXJ0EAUSCwoHZmlnaHRPcBAGEg0KCWRpc21p",
            "c3NlZBAHItABCgxGaWdodE1lc3NhZ2USLQoJYmF0dGxlQ01EGAEgASgOMhou",
            "cGIuRmlnaHRNZXNzYWdlLkJhdHRsZUNNRBIUCgxzZWxlY3RlZFVuaXQYAyAD",
            "KAUSEAoIc3RhcnRQb3MYBCABKAUSDgoGZW5kUG9zGAUgASgFEhEKCWVuZW15",
            "VW5pdBgGIAEoBRIWCg5pbnRlcmFjdE9iamVjdBgHIAEoBSIuCglCYXR0bGVD",
            "TUQSCAoEbW92ZRAAEgkKBWZpZ2h0EAESDAoIaW50ZXJhY3QQAkIGWgQuL3Bi",
            "YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Pb.AccountData), global::Pb.AccountData.Parser, new[]{ "Name" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Pb.SelectData), global::Pb.SelectData.Parser, new[]{ "PlayerName", "ChatMes", "Faction", "IsReady" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Pb.PbMessage), global::Pb.PbMessage.Parser, new[]{ "Name", "Cmd", "CmdMatch", "CmdRoom", "RoomIndex", "ChatMes", "SelectData", "RoomSelectData", "LoadPercent", "RoomLoadPercent", "FrameId", "SendFightMessage", "FightMessage" }, null, new[]{ typeof(global::Pb.PbMessage.Types.CMD), typeof(global::Pb.PbMessage.Types.CmdMatch), typeof(global::Pb.PbMessage.Types.CmdRoom) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Pb.FightMessage), global::Pb.FightMessage.Parser, new[]{ "BattleCMD", "SelectedUnit", "StartPos", "EndPos", "EnemyUnit", "InteractObject" }, null, new[]{ typeof(global::Pb.FightMessage.Types.BattleCMD) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class AccountData : pb::IMessage<AccountData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AccountData> _parser = new pb::MessageParser<AccountData>(() => new AccountData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AccountData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pb.ProtobufReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AccountData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AccountData(AccountData other) : this() {
      name_ = other.name_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AccountData Clone() {
      return new AccountData(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AccountData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AccountData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AccountData other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class SelectData : pb::IMessage<SelectData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SelectData> _parser = new pb::MessageParser<SelectData>(() => new SelectData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SelectData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pb.ProtobufReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SelectData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SelectData(SelectData other) : this() {
      playerName_ = other.playerName_;
      chatMes_ = other.chatMes_;
      faction_ = other.faction_;
      isReady_ = other.isReady_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SelectData Clone() {
      return new SelectData(this);
    }

    /// <summary>Field number for the "playerName" field.</summary>
    public const int PlayerNameFieldNumber = 2;
    private string playerName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PlayerName {
      get { return playerName_; }
      set {
        playerName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "chatMes" field.</summary>
    public const int ChatMesFieldNumber = 3;
    private string chatMes_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ChatMes {
      get { return chatMes_; }
      set {
        chatMes_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "faction" field.</summary>
    public const int FactionFieldNumber = 6;
    private int faction_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Faction {
      get { return faction_; }
      set {
        faction_ = value;
      }
    }

    /// <summary>Field number for the "isReady" field.</summary>
    public const int IsReadyFieldNumber = 7;
    private bool isReady_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsReady {
      get { return isReady_; }
      set {
        isReady_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SelectData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SelectData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PlayerName != other.PlayerName) return false;
      if (ChatMes != other.ChatMes) return false;
      if (Faction != other.Faction) return false;
      if (IsReady != other.IsReady) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (PlayerName.Length != 0) hash ^= PlayerName.GetHashCode();
      if (ChatMes.Length != 0) hash ^= ChatMes.GetHashCode();
      if (Faction != 0) hash ^= Faction.GetHashCode();
      if (IsReady != false) hash ^= IsReady.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (PlayerName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(PlayerName);
      }
      if (ChatMes.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ChatMes);
      }
      if (Faction != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(Faction);
      }
      if (IsReady != false) {
        output.WriteRawTag(56);
        output.WriteBool(IsReady);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (PlayerName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(PlayerName);
      }
      if (ChatMes.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ChatMes);
      }
      if (Faction != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(Faction);
      }
      if (IsReady != false) {
        output.WriteRawTag(56);
        output.WriteBool(IsReady);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (PlayerName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PlayerName);
      }
      if (ChatMes.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ChatMes);
      }
      if (Faction != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Faction);
      }
      if (IsReady != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SelectData other) {
      if (other == null) {
        return;
      }
      if (other.PlayerName.Length != 0) {
        PlayerName = other.PlayerName;
      }
      if (other.ChatMes.Length != 0) {
        ChatMes = other.ChatMes;
      }
      if (other.Faction != 0) {
        Faction = other.Faction;
      }
      if (other.IsReady != false) {
        IsReady = other.IsReady;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 18: {
            PlayerName = input.ReadString();
            break;
          }
          case 26: {
            ChatMes = input.ReadString();
            break;
          }
          case 48: {
            Faction = input.ReadInt32();
            break;
          }
          case 56: {
            IsReady = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 18: {
            PlayerName = input.ReadString();
            break;
          }
          case 26: {
            ChatMes = input.ReadString();
            break;
          }
          case 48: {
            Faction = input.ReadInt32();
            break;
          }
          case 56: {
            IsReady = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class PbMessage : pb::IMessage<PbMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PbMessage> _parser = new pb::MessageParser<PbMessage>(() => new PbMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PbMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pb.ProtobufReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PbMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PbMessage(PbMessage other) : this() {
      name_ = other.name_;
      cmd_ = other.cmd_;
      cmdMatch_ = other.cmdMatch_;
      cmdRoom_ = other.cmdRoom_;
      roomIndex_ = other.roomIndex_;
      chatMes_ = other.chatMes_;
      selectData_ = other.selectData_ != null ? other.selectData_.Clone() : null;
      roomSelectData_ = other.roomSelectData_.Clone();
      loadPercent_ = other.loadPercent_;
      roomLoadPercent_ = other.roomLoadPercent_.Clone();
      frameId_ = other.frameId_;
      sendFightMessage_ = other.sendFightMessage_ != null ? other.sendFightMessage_.Clone() : null;
      fightMessage_ = other.fightMessage_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PbMessage Clone() {
      return new PbMessage(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "cmd" field.</summary>
    public const int CmdFieldNumber = 2;
    private global::Pb.PbMessage.Types.CMD cmd_ = global::Pb.PbMessage.Types.CMD.Login;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Pb.PbMessage.Types.CMD Cmd {
      get { return cmd_; }
      set {
        cmd_ = value;
      }
    }

    /// <summary>Field number for the "cmdMatch" field.</summary>
    public const int CmdMatchFieldNumber = 3;
    private global::Pb.PbMessage.Types.CmdMatch cmdMatch_ = global::Pb.PbMessage.Types.CmdMatch.JoinMatch;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Pb.PbMessage.Types.CmdMatch CmdMatch {
      get { return cmdMatch_; }
      set {
        cmdMatch_ = value;
      }
    }

    /// <summary>Field number for the "cmdRoom" field.</summary>
    public const int CmdRoomFieldNumber = 4;
    private global::Pb.PbMessage.Types.CmdRoom cmdRoom_ = global::Pb.PbMessage.Types.CmdRoom.Confirm;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Pb.PbMessage.Types.CmdRoom CmdRoom {
      get { return cmdRoom_; }
      set {
        cmdRoom_ = value;
      }
    }

    /// <summary>Field number for the "roomIndex" field.</summary>
    public const int RoomIndexFieldNumber = 5;
    private int roomIndex_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int RoomIndex {
      get { return roomIndex_; }
      set {
        roomIndex_ = value;
      }
    }

    /// <summary>Field number for the "chatMes" field.</summary>
    public const int ChatMesFieldNumber = 6;
    private string chatMes_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ChatMes {
      get { return chatMes_; }
      set {
        chatMes_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "selectData" field.</summary>
    public const int SelectDataFieldNumber = 7;
    private global::Pb.SelectData selectData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Pb.SelectData SelectData {
      get { return selectData_; }
      set {
        selectData_ = value;
      }
    }

    /// <summary>Field number for the "roomSelectData" field.</summary>
    public const int RoomSelectDataFieldNumber = 8;
    private static readonly pb::FieldCodec<global::Pb.SelectData> _repeated_roomSelectData_codec
        = pb::FieldCodec.ForMessage(66, global::Pb.SelectData.Parser);
    private readonly pbc::RepeatedField<global::Pb.SelectData> roomSelectData_ = new pbc::RepeatedField<global::Pb.SelectData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Pb.SelectData> RoomSelectData {
      get { return roomSelectData_; }
    }

    /// <summary>Field number for the "loadPercent" field.</summary>
    public const int LoadPercentFieldNumber = 9;
    private int loadPercent_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int LoadPercent {
      get { return loadPercent_; }
      set {
        loadPercent_ = value;
      }
    }

    /// <summary>Field number for the "roomLoadPercent" field.</summary>
    public const int RoomLoadPercentFieldNumber = 10;
    private static readonly pb::FieldCodec<int> _repeated_roomLoadPercent_codec
        = pb::FieldCodec.ForInt32(82);
    private readonly pbc::RepeatedField<int> roomLoadPercent_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> RoomLoadPercent {
      get { return roomLoadPercent_; }
    }

    /// <summary>Field number for the "frameId" field.</summary>
    public const int FrameIdFieldNumber = 11;
    private int frameId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int FrameId {
      get { return frameId_; }
      set {
        frameId_ = value;
      }
    }

    /// <summary>Field number for the "sendFightMessage" field.</summary>
    public const int SendFightMessageFieldNumber = 12;
    private global::Pb.FightMessage sendFightMessage_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Pb.FightMessage SendFightMessage {
      get { return sendFightMessage_; }
      set {
        sendFightMessage_ = value;
      }
    }

    /// <summary>Field number for the "fightMessage" field.</summary>
    public const int FightMessageFieldNumber = 13;
    private static readonly pb::FieldCodec<global::Pb.FightMessage> _repeated_fightMessage_codec
        = pb::FieldCodec.ForMessage(106, global::Pb.FightMessage.Parser);
    private readonly pbc::RepeatedField<global::Pb.FightMessage> fightMessage_ = new pbc::RepeatedField<global::Pb.FightMessage>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Pb.FightMessage> FightMessage {
      get { return fightMessage_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PbMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PbMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (Cmd != other.Cmd) return false;
      if (CmdMatch != other.CmdMatch) return false;
      if (CmdRoom != other.CmdRoom) return false;
      if (RoomIndex != other.RoomIndex) return false;
      if (ChatMes != other.ChatMes) return false;
      if (!object.Equals(SelectData, other.SelectData)) return false;
      if(!roomSelectData_.Equals(other.roomSelectData_)) return false;
      if (LoadPercent != other.LoadPercent) return false;
      if(!roomLoadPercent_.Equals(other.roomLoadPercent_)) return false;
      if (FrameId != other.FrameId) return false;
      if (!object.Equals(SendFightMessage, other.SendFightMessage)) return false;
      if(!fightMessage_.Equals(other.fightMessage_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Cmd != global::Pb.PbMessage.Types.CMD.Login) hash ^= Cmd.GetHashCode();
      if (CmdMatch != global::Pb.PbMessage.Types.CmdMatch.JoinMatch) hash ^= CmdMatch.GetHashCode();
      if (CmdRoom != global::Pb.PbMessage.Types.CmdRoom.Confirm) hash ^= CmdRoom.GetHashCode();
      if (RoomIndex != 0) hash ^= RoomIndex.GetHashCode();
      if (ChatMes.Length != 0) hash ^= ChatMes.GetHashCode();
      if (selectData_ != null) hash ^= SelectData.GetHashCode();
      hash ^= roomSelectData_.GetHashCode();
      if (LoadPercent != 0) hash ^= LoadPercent.GetHashCode();
      hash ^= roomLoadPercent_.GetHashCode();
      if (FrameId != 0) hash ^= FrameId.GetHashCode();
      if (sendFightMessage_ != null) hash ^= SendFightMessage.GetHashCode();
      hash ^= fightMessage_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Cmd != global::Pb.PbMessage.Types.CMD.Login) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Cmd);
      }
      if (CmdMatch != global::Pb.PbMessage.Types.CmdMatch.JoinMatch) {
        output.WriteRawTag(24);
        output.WriteEnum((int) CmdMatch);
      }
      if (CmdRoom != global::Pb.PbMessage.Types.CmdRoom.Confirm) {
        output.WriteRawTag(32);
        output.WriteEnum((int) CmdRoom);
      }
      if (RoomIndex != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(RoomIndex);
      }
      if (ChatMes.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(ChatMes);
      }
      if (selectData_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(SelectData);
      }
      roomSelectData_.WriteTo(output, _repeated_roomSelectData_codec);
      if (LoadPercent != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(LoadPercent);
      }
      roomLoadPercent_.WriteTo(output, _repeated_roomLoadPercent_codec);
      if (FrameId != 0) {
        output.WriteRawTag(88);
        output.WriteInt32(FrameId);
      }
      if (sendFightMessage_ != null) {
        output.WriteRawTag(98);
        output.WriteMessage(SendFightMessage);
      }
      fightMessage_.WriteTo(output, _repeated_fightMessage_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Cmd != global::Pb.PbMessage.Types.CMD.Login) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Cmd);
      }
      if (CmdMatch != global::Pb.PbMessage.Types.CmdMatch.JoinMatch) {
        output.WriteRawTag(24);
        output.WriteEnum((int) CmdMatch);
      }
      if (CmdRoom != global::Pb.PbMessage.Types.CmdRoom.Confirm) {
        output.WriteRawTag(32);
        output.WriteEnum((int) CmdRoom);
      }
      if (RoomIndex != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(RoomIndex);
      }
      if (ChatMes.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(ChatMes);
      }
      if (selectData_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(SelectData);
      }
      roomSelectData_.WriteTo(ref output, _repeated_roomSelectData_codec);
      if (LoadPercent != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(LoadPercent);
      }
      roomLoadPercent_.WriteTo(ref output, _repeated_roomLoadPercent_codec);
      if (FrameId != 0) {
        output.WriteRawTag(88);
        output.WriteInt32(FrameId);
      }
      if (sendFightMessage_ != null) {
        output.WriteRawTag(98);
        output.WriteMessage(SendFightMessage);
      }
      fightMessage_.WriteTo(ref output, _repeated_fightMessage_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Cmd != global::Pb.PbMessage.Types.CMD.Login) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Cmd);
      }
      if (CmdMatch != global::Pb.PbMessage.Types.CmdMatch.JoinMatch) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) CmdMatch);
      }
      if (CmdRoom != global::Pb.PbMessage.Types.CmdRoom.Confirm) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) CmdRoom);
      }
      if (RoomIndex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RoomIndex);
      }
      if (ChatMes.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ChatMes);
      }
      if (selectData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SelectData);
      }
      size += roomSelectData_.CalculateSize(_repeated_roomSelectData_codec);
      if (LoadPercent != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(LoadPercent);
      }
      size += roomLoadPercent_.CalculateSize(_repeated_roomLoadPercent_codec);
      if (FrameId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(FrameId);
      }
      if (sendFightMessage_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SendFightMessage);
      }
      size += fightMessage_.CalculateSize(_repeated_fightMessage_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PbMessage other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Cmd != global::Pb.PbMessage.Types.CMD.Login) {
        Cmd = other.Cmd;
      }
      if (other.CmdMatch != global::Pb.PbMessage.Types.CmdMatch.JoinMatch) {
        CmdMatch = other.CmdMatch;
      }
      if (other.CmdRoom != global::Pb.PbMessage.Types.CmdRoom.Confirm) {
        CmdRoom = other.CmdRoom;
      }
      if (other.RoomIndex != 0) {
        RoomIndex = other.RoomIndex;
      }
      if (other.ChatMes.Length != 0) {
        ChatMes = other.ChatMes;
      }
      if (other.selectData_ != null) {
        if (selectData_ == null) {
          SelectData = new global::Pb.SelectData();
        }
        SelectData.MergeFrom(other.SelectData);
      }
      roomSelectData_.Add(other.roomSelectData_);
      if (other.LoadPercent != 0) {
        LoadPercent = other.LoadPercent;
      }
      roomLoadPercent_.Add(other.roomLoadPercent_);
      if (other.FrameId != 0) {
        FrameId = other.FrameId;
      }
      if (other.sendFightMessage_ != null) {
        if (sendFightMessage_ == null) {
          SendFightMessage = new global::Pb.FightMessage();
        }
        SendFightMessage.MergeFrom(other.SendFightMessage);
      }
      fightMessage_.Add(other.fightMessage_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 16: {
            Cmd = (global::Pb.PbMessage.Types.CMD) input.ReadEnum();
            break;
          }
          case 24: {
            CmdMatch = (global::Pb.PbMessage.Types.CmdMatch) input.ReadEnum();
            break;
          }
          case 32: {
            CmdRoom = (global::Pb.PbMessage.Types.CmdRoom) input.ReadEnum();
            break;
          }
          case 40: {
            RoomIndex = input.ReadInt32();
            break;
          }
          case 50: {
            ChatMes = input.ReadString();
            break;
          }
          case 58: {
            if (selectData_ == null) {
              SelectData = new global::Pb.SelectData();
            }
            input.ReadMessage(SelectData);
            break;
          }
          case 66: {
            roomSelectData_.AddEntriesFrom(input, _repeated_roomSelectData_codec);
            break;
          }
          case 72: {
            LoadPercent = input.ReadInt32();
            break;
          }
          case 82:
          case 80: {
            roomLoadPercent_.AddEntriesFrom(input, _repeated_roomLoadPercent_codec);
            break;
          }
          case 88: {
            FrameId = input.ReadInt32();
            break;
          }
          case 98: {
            if (sendFightMessage_ == null) {
              SendFightMessage = new global::Pb.FightMessage();
            }
            input.ReadMessage(SendFightMessage);
            break;
          }
          case 106: {
            fightMessage_.AddEntriesFrom(input, _repeated_fightMessage_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 16: {
            Cmd = (global::Pb.PbMessage.Types.CMD) input.ReadEnum();
            break;
          }
          case 24: {
            CmdMatch = (global::Pb.PbMessage.Types.CmdMatch) input.ReadEnum();
            break;
          }
          case 32: {
            CmdRoom = (global::Pb.PbMessage.Types.CmdRoom) input.ReadEnum();
            break;
          }
          case 40: {
            RoomIndex = input.ReadInt32();
            break;
          }
          case 50: {
            ChatMes = input.ReadString();
            break;
          }
          case 58: {
            if (selectData_ == null) {
              SelectData = new global::Pb.SelectData();
            }
            input.ReadMessage(SelectData);
            break;
          }
          case 66: {
            roomSelectData_.AddEntriesFrom(ref input, _repeated_roomSelectData_codec);
            break;
          }
          case 72: {
            LoadPercent = input.ReadInt32();
            break;
          }
          case 82:
          case 80: {
            roomLoadPercent_.AddEntriesFrom(ref input, _repeated_roomLoadPercent_codec);
            break;
          }
          case 88: {
            FrameId = input.ReadInt32();
            break;
          }
          case 98: {
            if (sendFightMessage_ == null) {
              SendFightMessage = new global::Pb.FightMessage();
            }
            input.ReadMessage(SendFightMessage);
            break;
          }
          case 106: {
            fightMessage_.AddEntriesFrom(ref input, _repeated_fightMessage_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the PbMessage message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum CMD {
        [pbr::OriginalName("login")] Login = 0,
        [pbr::OriginalName("match")] Match = 1,
        [pbr::OriginalName("room")] Room = 2,
        /// <summary>
        /// 这个fight只是服务器发客户端
        /// </summary>
        [pbr::OriginalName("fight")] Fight = 3,
        [pbr::OriginalName("chat")] Chat = 4,
        [pbr::OriginalName("fightEnd")] FightEnd = 5,
      }

      public enum CmdMatch {
        [pbr::OriginalName("joinMatch")] JoinMatch = 0,
        [pbr::OriginalName("quitMatch")] QuitMatch = 1,
      }

      public enum CmdRoom {
        [pbr::OriginalName("confirm")] Confirm = 0,
        [pbr::OriginalName("select")] Select = 1,
        [pbr::OriginalName("selectDate")] SelectDate = 2,
        [pbr::OriginalName("load")] Load = 3,
        [pbr::OriginalName("loadData")] LoadData = 4,
        [pbr::OriginalName("fightStart")] FightStart = 5,
        /// <summary>
        ///这个fightop只是客户端发服务器
        /// </summary>
        [pbr::OriginalName("fightOp")] FightOp = 6,
        [pbr::OriginalName("dismissed")] Dismissed = 7,
      }

    }
    #endregion

  }

  public sealed partial class FightMessage : pb::IMessage<FightMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<FightMessage> _parser = new pb::MessageParser<FightMessage>(() => new FightMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<FightMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pb.ProtobufReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FightMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FightMessage(FightMessage other) : this() {
      battleCMD_ = other.battleCMD_;
      selectedUnit_ = other.selectedUnit_.Clone();
      startPos_ = other.startPos_;
      endPos_ = other.endPos_;
      enemyUnit_ = other.enemyUnit_;
      interactObject_ = other.interactObject_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FightMessage Clone() {
      return new FightMessage(this);
    }

    /// <summary>Field number for the "battleCMD" field.</summary>
    public const int BattleCMDFieldNumber = 1;
    private global::Pb.FightMessage.Types.BattleCMD battleCMD_ = global::Pb.FightMessage.Types.BattleCMD.Move;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Pb.FightMessage.Types.BattleCMD BattleCMD {
      get { return battleCMD_; }
      set {
        battleCMD_ = value;
      }
    }

    /// <summary>Field number for the "selectedUnit" field.</summary>
    public const int SelectedUnitFieldNumber = 3;
    private static readonly pb::FieldCodec<int> _repeated_selectedUnit_codec
        = pb::FieldCodec.ForInt32(26);
    private readonly pbc::RepeatedField<int> selectedUnit_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> SelectedUnit {
      get { return selectedUnit_; }
    }

    /// <summary>Field number for the "startPos" field.</summary>
    public const int StartPosFieldNumber = 4;
    private int startPos_;
    /// <summary>
    /// move
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int StartPos {
      get { return startPos_; }
      set {
        startPos_ = value;
      }
    }

    /// <summary>Field number for the "endPos" field.</summary>
    public const int EndPosFieldNumber = 5;
    private int endPos_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int EndPos {
      get { return endPos_; }
      set {
        endPos_ = value;
      }
    }

    /// <summary>Field number for the "enemyUnit" field.</summary>
    public const int EnemyUnitFieldNumber = 6;
    private int enemyUnit_;
    /// <summary>
    ///fight
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int EnemyUnit {
      get { return enemyUnit_; }
      set {
        enemyUnit_ = value;
      }
    }

    /// <summary>Field number for the "interactObject" field.</summary>
    public const int InteractObjectFieldNumber = 7;
    private int interactObject_;
    /// <summary>
    ///interact
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int InteractObject {
      get { return interactObject_; }
      set {
        interactObject_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as FightMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(FightMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (BattleCMD != other.BattleCMD) return false;
      if(!selectedUnit_.Equals(other.selectedUnit_)) return false;
      if (StartPos != other.StartPos) return false;
      if (EndPos != other.EndPos) return false;
      if (EnemyUnit != other.EnemyUnit) return false;
      if (InteractObject != other.InteractObject) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (BattleCMD != global::Pb.FightMessage.Types.BattleCMD.Move) hash ^= BattleCMD.GetHashCode();
      hash ^= selectedUnit_.GetHashCode();
      if (StartPos != 0) hash ^= StartPos.GetHashCode();
      if (EndPos != 0) hash ^= EndPos.GetHashCode();
      if (EnemyUnit != 0) hash ^= EnemyUnit.GetHashCode();
      if (InteractObject != 0) hash ^= InteractObject.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (BattleCMD != global::Pb.FightMessage.Types.BattleCMD.Move) {
        output.WriteRawTag(8);
        output.WriteEnum((int) BattleCMD);
      }
      selectedUnit_.WriteTo(output, _repeated_selectedUnit_codec);
      if (StartPos != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(StartPos);
      }
      if (EndPos != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(EndPos);
      }
      if (EnemyUnit != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(EnemyUnit);
      }
      if (InteractObject != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(InteractObject);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (BattleCMD != global::Pb.FightMessage.Types.BattleCMD.Move) {
        output.WriteRawTag(8);
        output.WriteEnum((int) BattleCMD);
      }
      selectedUnit_.WriteTo(ref output, _repeated_selectedUnit_codec);
      if (StartPos != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(StartPos);
      }
      if (EndPos != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(EndPos);
      }
      if (EnemyUnit != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(EnemyUnit);
      }
      if (InteractObject != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(InteractObject);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (BattleCMD != global::Pb.FightMessage.Types.BattleCMD.Move) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) BattleCMD);
      }
      size += selectedUnit_.CalculateSize(_repeated_selectedUnit_codec);
      if (StartPos != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(StartPos);
      }
      if (EndPos != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(EndPos);
      }
      if (EnemyUnit != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(EnemyUnit);
      }
      if (InteractObject != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(InteractObject);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(FightMessage other) {
      if (other == null) {
        return;
      }
      if (other.BattleCMD != global::Pb.FightMessage.Types.BattleCMD.Move) {
        BattleCMD = other.BattleCMD;
      }
      selectedUnit_.Add(other.selectedUnit_);
      if (other.StartPos != 0) {
        StartPos = other.StartPos;
      }
      if (other.EndPos != 0) {
        EndPos = other.EndPos;
      }
      if (other.EnemyUnit != 0) {
        EnemyUnit = other.EnemyUnit;
      }
      if (other.InteractObject != 0) {
        InteractObject = other.InteractObject;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            BattleCMD = (global::Pb.FightMessage.Types.BattleCMD) input.ReadEnum();
            break;
          }
          case 26:
          case 24: {
            selectedUnit_.AddEntriesFrom(input, _repeated_selectedUnit_codec);
            break;
          }
          case 32: {
            StartPos = input.ReadInt32();
            break;
          }
          case 40: {
            EndPos = input.ReadInt32();
            break;
          }
          case 48: {
            EnemyUnit = input.ReadInt32();
            break;
          }
          case 56: {
            InteractObject = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            BattleCMD = (global::Pb.FightMessage.Types.BattleCMD) input.ReadEnum();
            break;
          }
          case 26:
          case 24: {
            selectedUnit_.AddEntriesFrom(ref input, _repeated_selectedUnit_codec);
            break;
          }
          case 32: {
            StartPos = input.ReadInt32();
            break;
          }
          case 40: {
            EndPos = input.ReadInt32();
            break;
          }
          case 48: {
            EnemyUnit = input.ReadInt32();
            break;
          }
          case 56: {
            InteractObject = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the FightMessage message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum BattleCMD {
        [pbr::OriginalName("move")] Move = 0,
        [pbr::OriginalName("fight")] Fight = 1,
        [pbr::OriginalName("interact")] Interact = 2,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
